name: Run Python

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python main.py
